spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222
